name: licensehash_key_generator
description: "The application generate Licenses Keys and there hashes."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  # hash the key
  crypto: ^3.0.6 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
